apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api-app
  template:
    metadata:
      labels:
        app: fast-api-app
    spec:
      containers:
      - name: fast-api-container
        image: fast-api-image
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: fast-api-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
